config/routes.rb
Rails.application.routes.draw do
  root 'feed_items#index'

  resources :feeds, only: [:index, :new, :create]
  resources :feed_items, only: [:index, :show, :update]
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  has_many :feed_items, dependent: :destroy

  validates :url, uniqueness: true

  def display_name
    name || url
  end
end

app/models/feed_item.rb
class FeedItem < ActiveRecord::Base
  include Workflow

  belongs_to :feed

  scope :unread, -> { where.not(workflow_state: :read) }

  workflow do
    state :new do
      event :read, transitions_to: :read
    end
    state :read do
      event :unread, transitions_to: :unread
    end
    state :unread do
      event :read, transitions_to: :read
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :refresh_feeds

  def refresh_feeds
    SynchronizeFeedsJob.perform_later
  end
end

app/controllers/feed_items_controller.rb
class FeedItemsController < ApplicationController
  before_action :load_feed_item, only: [:show, :update]

  def index
    @feed_items = if params[:feed_id]
      FeedItem.where(feed_id: params[:feed_id])
    else
      FeedItem.unread
    end
  end

  def show
    @feed_item.read! unless @feed_item.read?
    redirect_to @feed_item.url
  end

  def update
    unread! if params[:mark_unread]
  end

  private

  def unread!
    @feed_item.unread!
    flash[:notice] = "Item marked unread"
    redirect_to 'index'
  end

  def load_feed_item
    @feed_item = FeedItem.find(params[:id])
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def index
    @feeds = Feed.all
  end

  def new
    @feed = Feed.new
  end

  def create
    @feed = Feed.new(feed_params)
    if @feed.save
      SynchronizeFeedsJob.perform_later(feed.id)
      flash[:notice] = "New feed successfully added!"
      redirect_to feeds_url
    else
      flash[:error] = "Unable to add new feed. #{@feed.errors.full_messages.join('. ')}"
      render :new
    end
  end

  private

  def feed_params
    params.require(:feed).permit(:url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/feed_items/index.html.erb
<div class="feed-items-index">
  <%= link_to "Feeds", feeds_path %>

  <div class="feed-items">
    <% @feed_items.each do |item| %>
      <div class="feed-item <%= 'read' if item.read? %>">
        <span class="feed-item__feed-name"><%= item.feed.name %></span>
        <span class="feed-item__title"><%= link_to item.title, item, target: '_blank' %></span>
      </div>
    <% end %>
  </div>

</div>

app/views/feeds/index.html.erb
<div class="feeds-index">
  <%= link_to "Home", feed_items_path %>

  <% @feeds.each do |feed| %>
    <div class="feed item">
      <span class="item__name"><%= link_to feed.display_name, feed_items_path(feed_id: feed.id) %></span>
      <span class="feed__unread item__text"><%= feed.feed_items.unread.count %> unread</span>
    </div>
  <% end %>

  <%= link_to "Add", new_feed_path %>
</div>

app/views/feeds/new.html.erb
<%= form_for @feed do |f| %>
  <%= f.label :url %>
  <%= f.text_field :url %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RssReader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if flash[:notice] %>
    <div class="flash flash--notice">
      <%= flash[:notice] %>
    </div>
  <% end %>

<%= yield %>

</body>
</html>